### ISSUE TITLE
PromotionPack missing

### ISSUE THREAD

**Issue by irmafazira** [irmafazira/SCM_GROUP1_MiniProject#3]
There are some errors with previous PromotionPack files and I have to delete both. Can someone upload PromotionPack.aspx and PromotionPack.aspx.cs and put both under Package folder?

Thanks.

**Comment by nafiqaht** [comment]
There are minor error in PromotionPack.aspx. I've update the PromotionPack files, and corrected the errors. I have uploaded PromotionPack.aspx and PromotionPack.aspx.cs under Package Folder.

Regards, 
Afiqah
